Necessary configuration functions updated

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,89 @@
 #!/bin/bash
+set -e -o pipefail
+cd `dirname $0`
+
+ROOT="/etc/scl"
+DECORER="$ROOT/decoder"
+IDS="$ROOT/ids"
+CONFIGURATION_DIRECTORY="$ROOT/config/agent"
+LOG_PATH="/etc/scl/log/" 
+echo "Checking Configuration directories.."
+
+#creating root directory
+if [ ! -d "$ROOT" ]; then
+    echo "Root directory not found..."
+    echo "Creating root directory..."
+    mkdir -p "$ROOT"
+else
+    echo "Root directory found..."
+fi
+
+#check and create configuration directory
+if [ ! -d "$CONFIGURATION_DIRECTORY" ]; then
+    echo "Building Configuration directories..."
+    mkdir -p $"CONFIGURATION_DIRECTORY" 
+    echo "Directory created: $CONFIGURATION_DIRECTORY"
+else
+    echo "Directory already exists: $CONFIGURATION_DIRECTORY"
+fi
+
+#check and create configuration files
+if [ ! -f "$CONFIGURATION_DIRECTORY/agent.config" ]; then   
+    echo "Agent configuration not found..."
+    echo "Writing new agent configuration file..."
+    cp config/agent.config "$CONFIGURATION_DIRECTORY"
+else
+    echo "Agent configuration file found..."
+fi
+
+if [ ! -f "$CONFIGURATION_DIRECTORY/agent.config" ]; then 
+    echo "Schedule configuration not found..."
+    echo "Writing new schedule configuration file..."
+    cp config/schedule.config "$CONFIGURATION_DIRECTORY"
+else    
+    echo "Schedule configuration file found..."
+fi
+
+#check and create decoder directory and copy the decoder files
+if [ ! -d "$DECODER" ]; then
+    echo "Decoder directory not found..."
+    echo "Creating decoder directory..."
+    mkdir -p "$DECODER"
+else
+    echo "Decoder directory found..."
+fi
+
+if [ ! -d "$DECODER/decoder.xml" ]; then
+    echo "Decoder file not found writing decoer file..."
+    cp decoder.xml "$DECODER"
+else    
+    echo "Decoder file exists"
+fi
+
+#check and create rules directory and add the ossec rules
+ls -la "$ROOT/rules" > /dev/null 2>&1
+if [ ! $? = 0 ]; then
+    echo "Rules directory is emtpty adding rules..."
+    cp -rf rules "$ROOT"
+else    
+    echo "Rules directory not empty..."
+fi     
+
+if [ ! -d "$LOG_PATH" ]; then
+    echo "Log directory not found..."
+    echo "Creating new directoy:  $LOG_PATH"
+    mkdir -p "$LOG_PATH" 
+else
+    echo "Found log directory: $LOG_PATH"
+fi
+
+if [ ! -f "$LOG_PATH/agent.log" ]; then
+    echo "Log file not found..."
+    echo "Log file created under: $LOG_PATH"
+    touch "$LOG_PATH/agent.log" 
+else   
+    echo "Log file found:  $LOG_PATH/agent.log"
+fi
 
 # Check if necessary tools are available
 command -v g++ >/dev/null 2>&1 || { echo >&2 "g++ is required but not installed. Aborting."; exit 1; }
@@ -9,14 +94,14 @@ if pkg-config --exists pugixml; then
     echo "pugixml found."
 else
     echo "pugixml not found. Downloading and building..."
-    git submodule update --init --recursive
-    cd pugixml
-    mkdir build
-    cd build
-    cmake ..
-    make
+    git clone $PUGI_XML_GIT_URL
+    cd pugixml 
+    mkdir build 
+    cd build 
+    cmake .. 
+    make 
 
-    cd ../..
+    cd ../.. 
     echo "pugixml downloaded and built successfully"
 fi
 
@@ -25,7 +110,7 @@ if pkg-config --exists libcurl; then
 else 
     echo "libcurl not found. Installing..."
     sudo apt update
-    sudo apt install -y libcurl4-openssl-dev
+    sudo apt install -y libcurl4-openssl-dev 
     echo "libcurl installed successfully"
 fi
 
@@ -85,6 +170,5 @@ if pkg-config --exists amqpcpp; then
         echo "libev downloaded and built successfully"
     fi
 fi
-
 
 echo "Configuration complete."
